2021-12-22 13:40:34.056321: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-12-22 13:40:34.056361: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
tf:  2.6.0
tb:  2.7.0
/home/chau/workingdir/tf_implementations/bash_scripts
{'batchSize': 4.0, 'numTrainingSteps': 40000.0, 'beta1': 0.943377, 'beta2': 0.97205, 'epsilon': 8.62125e-05, 'decayDurationFactor': 0.98628, 'initialLearningRate': 0.002, 'learningRateDecay': 0.006226, 'glorotScaleFactor': 0.1, 'orthogonalScaleFactor': 0.1, 'testSize': 0.5}
No. of arguments passed is  5
Argument #0 is ./RNNplus_v1_4_1Datasets.py
Argument #1 is ../../Datasets/1_5_big_datasets/bigdatasets/seqnetdata.ni=14.no=19.mc=221.numTimeSteps300.52.csv
Argument #2 is LSTM
Argument #3 is False
Argument #4 is False
Dataset:  lstm_wLRS_wCMF_tf_14_19_221_300
Step 3: Training....
Traceback (most recent call last):
  File "./RNNplus_v1_4_1Datasets.py", line 392, in <module>
    main(datasetpath, modeltype, isLRS, isCMF)
  File "./RNNplus_v1_4_1Datasets.py", line 353, in main
    model =  models(modeltype=modeltype, timestep=timestep, noInput=noIn, noOutput=noOut, batchSize=int(hyperparams['batchSize']), isLRS=isLRS, isCMF=isCMF).chooseModels()
  File "./RNNplus_v1_4_1Datasets.py", line 310, in chooseModels
    display(prefix)
NameError: name 'display' is not defined
